CREATE DATABASE IF NOT EXISTS account;
CREATE DATABASE IF NOT EXISTS orderdb;
CREATE DATABASE IF NOT EXISTS inventory;

CREATE USER IF NOT EXISTS 'springcloud'@'%' IDENTIFIED BY 'springcloud123';
GRANT ALL PRIVILEGES ON *.* TO 'springcloud'@'%';
FLUSH PRIVILEGES;

ALTER USER 'root'@'%' IDENTIFIED BY '123';
FLUSH PRIVILEGES;