server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        fail-fast: false
        retry:
          times: 10
          interval: 5000
        username: nacos
        password: nacos
    compatibility-verifier:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info